name: Build Windows Portable

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build portable
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-portable
          path: dist/*.exe
